[minimp]
appid='minimp'
secret='minimp'

[timezone]
timezone='Asia/Shanghai'
datetime_format='%Y-%m-%d %H:%M:%S'

[dtk]
apiUrl='https://openapi.dataoke.com/api/'
appKey='5dc6fcef48989'
appSerect='17eda35413998548b3fdebd31e6d2c51'
version='v1.2.0'

[cache]
dir='cache'

[app]
DEBUG=true
SECRET_KEY="tI_inQ#O!Qb(x=!W$:E?,F.1_#p&b!'sOKuwy7VXym%1*r<;URdzM`Ds$sSv2QW"
CSRF_TRUSTED_ORIGINS=["http://django.lazyfury.fun","http://127.0.0.1:8000"]
SITE_URL="http://127.0.0.1"