# Generated by Django 5.0 on 2024-01-23 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_url', models.CharField(blank=True, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('normal', '正常'), ('deleted', '已删除'), ('disabled', '禁用')], default='normal', max_length=10)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '短链',
                'verbose_name_plural': '短链',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('originUrl', models.URLField(blank=True, max_length=2000, null=True)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, editable=False, upload_to='')),
                ('type', models.CharField(choices=[('URL', '超链接'), ('TEXT', '文本')], default='URL', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('short', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urlzip.link')),
            ],
            options={
                'verbose_name': '二维码',
                'verbose_name_plural': '二维码',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VisitorIP',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urlzip.link')),
            ],
            options={
                'verbose_name': '短链访客IP记录',
                'verbose_name_plural': '短链访客IP记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
