# Generated by Django 5.0 on 2024-01-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlzip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='ip',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='type',
            field=models.CharField(choices=[('URL', '超链接'), ('TEXT', '文本')], default='TEXT', max_length=10),
        ),
    ]
