# Generated by Django 5.0 on 2024-01-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productbrand_productcategory_productskugroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skus',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.productskugroup'),
        ),
    ]
