# Generated by Django 5.0 on 2024-01-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_skus'),
    ]

    operations = [
        migrations.AddField(
            model_name='productskugroup',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='skus_set', to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skus',
            field=models.ManyToManyField(blank=True, related_name='products_set', to='store.productskugroup'),
        ),
    ]
