# Generated by Django 4.2.7 on 2023-11-29 01:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_qrcode_created_at_qrcode_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='short',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link.link'),
        ),
        migrations.AlterField(
            model_name='wxqrcode',
            name='timeout',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 6, 9, 16, 22, 500119), help_text='默认 7 天过期', null=True),
        ),
    ]
