# Generated by Django 5.0 on 2023-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_alter_qrcode_short_alter_wxqrcode_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='wx',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='type',
            field=models.CharField(choices=[('URL', '超链接'), ('TEXT', '文本')], default='URL', max_length=10),
        ),
        migrations.DeleteModel(
            name='WXQRCode',
        ),
    ]
