# Generated by Django 5.0 on 2024-01-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_link_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='sortUrl',
            field=models.CharField(blank=True, db_column='sortUrl', max_length=10, unique=True),
        ),
        migrations.RenameField(
            model_name='link',
            old_name='sortUrl',
            new_name='sort_url',
        ),
        migrations.RemoveField(
            model_name='link',
            name='clickCount',
        ),
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('deleted', '已删除'), ('disabled', '禁用')], default='normal', max_length=10),
        ),
    ]
