# Generated by Django 5.0 on 2024-01-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_alter_link_sorturl_rename_sorturl_link_sort_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='sort_url',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
