# Generated by Django 4.2.7 on 2023-11-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_usermodel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="1997-01-01"),  # type: ignore
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermodel",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
