# Generated by Django 5.0 on 2023-12-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userinvitecode_userinviterelate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinviterelate',
            name='a_b_id',
            field=models.CharField(default=1, max_length=10, unique=True), # type: ignore
            preserve_default=False,
        ),
    ]
