# Generated by Django 5.0 on 2023-12-05 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userinviterelate_a_b_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinviterelate',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belong', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinviterelate',
            name='a_b_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
