# Generated by Django 5.0 on 2023-12-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userinviterelate_belong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinviterelate',
            name='a_b_id',
        ),
        migrations.AddField(
            model_name='userinviterelate',
            name='invite_user_unique_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
