# Generated by Django 5.0 on 2023-12-05 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_userinviterelate_a_b_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitecode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
