# Generated by Django 5.0 on 2024-01-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usertoken_browser_usertoken_device_usertoken_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='ua',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
