# Generated by Django 5.0 on 2024-02-01 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_usermodel_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableManager',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('api_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('delete_api_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_api_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('update_api_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('columns', models.CharField(blank=True, max_length=1000, null=True)),
                ('search_form_fields', models.CharField(blank=True, max_length=1000, null=True)),
                ('edit_form_fields', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
