# Generated by Django 5.0 on 2024-02-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_default',
        ),
    ]
