# Generated by Django 5.0 on 2024-02-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemanager',
            name='key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
