# Generated by Django 5.0 on 2024-02-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_tablemanager_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemanager',
            name='create_api_url',
        ),
        migrations.RemoveField(
            model_name='tablemanager',
            name='delete_api_url',
        ),
        migrations.RemoveField(
            model_name='tablemanager',
            name='update_api_url',
        ),
    ]
