# Generated by Django 5.0 on 2024-02-19 08:31

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_tablemanager_create_api_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemanager',
            name='columns',
            field=core.models.JSONField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='tablemanager',
            name='edit_form_fields',
            field=core.models.JSONField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='tablemanager',
            name='search_form_fields',
            field=core.models.JSONField(blank=True, max_length=10000, null=True),
        ),
    ]
