# Generated by Django 5.0 on 2024-02-20 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_menu_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tablemanager'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='pid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
