# Generated by Django 5.0 on 2024-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_tablemanager_enable_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='enable_delete',
            field=models.BooleanField(default=False),
        ),
    ]
