# Generated by Django 5.0 on 2024-02-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_permission_enable_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
