# Generated by Django 5.0 on 2024-02-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_dictgroup_dict'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dict',
            new_name='DictValue',
        ),
    ]
