# Generated by Django 5.0 on 2024-02-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_dict_dictvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hidden_on_menu',
            field=models.BooleanField(default=False),
        ),
    ]
