# Generated by Django 5.0 on 2024-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_menu_hidden_on_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='permission_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
