# Generated by Django 5.0 on 2024-02-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_menu_permission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='permission_code',
            field=models.CharField(blank=True, default='#', max_length=100, null=True),
        ),
    ]
