# Generated by Django 5.0 on 2024-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_menu_permission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
